image: valian/docker-python-opencv-ffmpeg
before_script:
  - apt-get update && apt-get install -y ruby
  - ruby -v
  - pip install git+https://github.com/misasa/image_mosaic.git
  - gem install bundler
  - bundle install

test:
  script:
  - bundle exec rake spec